use_frameworks!

platform :ios, '9.0'

target 'CDAuthorizationTool_Example' do
  pod 'CDAuthorizationTool', :path => '../'

  target 'CDAuthorizationTool_Tests' do
    inherit! :search_paths

    
  end
end
